---
name: code-npm-publish-snapshot
run-name: "Publish snapshot: ${{ github.event.issue.title }}"

concurrency: code-publish-snapshot-${{ github.ref }}

on:
  issue_comment:
    types: [created]

# permissions:
#   id-token: write # Required for OIDC

jobs:
  publish-snapshot:
    name: Publish Snapshot
    if: >
      github.event.issue.pull_request != null &&
      github.event.comment.body == '/publish-snapshot'
    runs-on: ubuntu-24.04
    env:
      ASDF_BRANCH_VERSION: 0.18.0
    steps:
      - name: Validate admin permissions
        id: permission-check
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.repos.getCollaboratorPermissionLevel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: context.actor
            });

            const permission = data.permission;
            core.info(`User permission level: ${permission}`);

            if (permission !== 'admin') {
              core.setFailed(`User @${context.actor} is not a repository admin.`);
            }

      - name: Get input parameters
        run: |
          RELEASE_LABELS="${{ join(github.event.issue.labels.*.name, ', ') }}"
          if [[ $RELEASE_LABELS != *release-type/* ]]; then
            RELEASE_LABELS="$RELEASE_LABELS, release-type/minor"
          fi
          echo "RELEASE_LABELS=$RELEASE_LABELS" >> "$GITHUB_ENV"
          BASELINE_BRANCH=${{ github.ref }}
          echo "BASELINE_BRANCH=${BASELINE_BRANCH#refs/heads/}" >> "$GITHUB_ENV"

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
          fetch-depth: 0
          persist-credentials: false

      - name: NPM / Setup Dependencies Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('code/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup asdf Cache
        id: asdf-cache
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: ~/.asdf
          key: ${{ runner.os }}-asdf-${{ env.ASDF_BRANCH_VERSION }}-${{ hashFiles('code/.tool-versions') }}

      - name: Save tool-versions content
        run: |
          {
            echo "TOOL_VERSIONS<<EOF"
            cat code/.tool-versions
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Setup asdf environment
        uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302 # v4.0.0
        # https://github.com/asdf-vm/actions/issues/356
        if: steps.asdf-cache.outputs.cache-hit != 'true'
        with:
          tool_versions: ${{ env.TOOL_VERSIONS }}
          asdf_version: ${{ env.ASDF_BRANCH_VERSION }}

      - name: NPM / Set npmrc
        env:
          NPM_AUTH: ${{ secrets.NPM_TOKEN }}
          NPM_REGISTRY: "https://registry.npmjs.org/"
        run: |
          echo "registry=${NPM_REGISTRY}" >> /home/runner/.npmrc
          echo "@inditextech:registry=${NPM_REGISTRY}" >> /home/runner/.npmrc
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH}" >> /home/runner/.npmrc
          echo "always-auth=true" >> /home/runner/.npmrc

      - name: NPM / Create Cache Folders
        run: |
          mkdir -p "$HOME"/.npm

      - name: Setup patch release type version
        if: contains(env.RELEASE_LABELS, 'release-type/hotfix')
          || contains(env.RELEASE_LABELS, 'release-type/multi-hotfix')
          || contains(env.RELEASE_LABELS, 'release-type/patch')
        run: echo "RELEASE_VERSION=patch" >> "$GITHUB_ENV"

      - name: Setup minor release type version
        if: contains(env.RELEASE_LABELS, 'release-type/minor')
        run: echo "RELEASE_VERSION=minor" >> "$GITHUB_ENV"

      - name: Setup minor release type version when no label set and TBD
        if: ${{ !contains(env.RELEASE_LABELS, 'release-type') && vars.DEVELOPMENT_FLOW == 'trunk-based-development' }}
        run: echo "RELEASE_VERSION=minor" >> "$GITHUB_ENV"

      - name: Setup major release type version
        if: contains(env.RELEASE_LABELS, 'release-type/major')
        run: echo "RELEASE_VERSION=major" >> "$GITHUB_ENV"

      - name: Update CHANGELOG.md
        id: update-changelog
        uses: release-flow/keep-a-changelog-action@v3.0.0
        with:
          command: bump
          version: ${{ env.RELEASE_VERSION }}
          changelog: code/CHANGELOG.md
          fail-on-empty-release-notes: false
          keep-unreleased-section: true
          tag-prefix: ""

      - name: Define snapshot version
        working-directory: code
        env:
          RELEASE_VERSION: ${{ steps.update-changelog.outputs.version }}
        run: |
          CLEAN_VERSION=$(echo "$RELEASE_VERSION" | sed -E 's/-.*$//')
          PRE_RELEASE_VERSION="${CLEAN_VERSION}-SNAPSHOT.${{ github.run_number }}.${{ github.run_attempt }}"
          echo "SNAPSHOT_VERSION=$PRE_RELEASE_VERSION" >> "$GITHUB_ENV"

      - name: NPM / Prepare snapshot
        working-directory: code
        env:
          RELEASE_VERSION: ${{ env.SNAPSHOT_VERSION }}
        run: |
          npm run version:release
          npm run release:prepare

      - name: NPM / Publish Snapshot - Distribution Platform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: code
        run: |
          npm run publish:snapshot

      - name: Result / Comment on PR
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{ job.status }}';

            const body = status === 'success'
              ? [
                  "✅ Pre-release published successfully.",
                  "",
                  `- Version: \`${process.env.SNAPSHOT_VERSION}\``,
                  "- Tag: `next`"
                ]
              : [
                  "❌ Pre-release publish failed.",
                  "",
                  "Please check the workflow logs for details."
                ]

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body.join("\n")
            });
